//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EratoWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EratoWPF.Resources.TextFile", typeof(TextFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This small program finds all prime numbers in specified range. To achieve that it uses Sieve of Erathosthenes..
        /// </summary>
        public static string appDescription {
            get {
                return ResourceManager.GetString("appDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EratoWPF - Sieve of Eratosthenes.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string btnClearConsole {
            get {
                return ResourceManager.GetString("btnClearConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run!.
        /// </summary>
        public static string btnRun {
            get {
                return ResourceManager.GetString("btnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as TXT.
        /// </summary>
        public static string btnSaveAsTxt {
            get {
                return ResourceManager.GetString("btnSaveAsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        public static string completedMsg {
            get {
                return ResourceManager.GetString("completedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sieve of Erathosthenes has completed finding
        ///all prime numbers in provided range..
        /// </summary>
        public static string completedText {
            get {
                return ResourceManager.GetString("completedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating dataset....
        /// </summary>
        public static string consoleDataSet {
            get {
                return ResourceManager.GetString("consoleDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string consoleDay {
            get {
                return ResourceManager.GetString("consoleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string consoleDays {
            get {
                return ResourceManager.GetString("consoleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime numbers found:.
        /// </summary>
        public static string consoleFound {
            get {
                return ResourceManager.GetString("consoleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output console.
        /// </summary>
        public static string consoleOutput {
            get {
                return ResourceManager.GetString("consoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed in:.
        /// </summary>
        public static string consoleProcessTime {
            get {
                return ResourceManager.GetString("consoleProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string consoleReady {
            get {
                return ResourceManager.GetString("consoleReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.....
        /// </summary>
        public static string consoleRunning {
            get {
                return ResourceManager.GetString("consoleRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string menuClose {
            get {
                return ResourceManager.GetString("menuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mkajzer.pl.
        /// </summary>
        public static string menuWWW {
            get {
                return ResourceManager.GetString("menuWWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This implementation uses int variable type. Maximum allowed number is 2147483647..
        /// </summary>
        public static string rangeDescription {
            get {
                return ResourceManager.GetString("rangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range end: .
        /// </summary>
        public static string rangeEnd {
            get {
                return ResourceManager.GetString("rangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide range boundries:.
        /// </summary>
        public static string rangeInput {
            get {
                return ResourceManager.GetString("rangeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range start: .
        /// </summary>
        public static string rangeStart {
            get {
                return ResourceManager.GetString("rangeStart", resourceCulture);
            }
        }
    }
}
